30-seconds/30-seconds-web

- config.js
- gatsby-browser.js
- gatsby-config.js
- package-lock.json
- package.json
- src/atoms/meta/index.jsx
- src/engines/recommendationEngine.js
- src/functions/build/createPages/createCookiePage.js
- src/functions/build/createPages/index.js
- src/lang/literals_en.js
- src/molecules/_index.scss
- src/molecules/cookieConsentPopup/_index.scss
- src/molecules/cookieConsentPopup/cookieConsentPopup.stories.js
- src/molecules/cookieConsentPopup/cookieConsentPopup.test.jsx
- src/molecules/cookieConsentPopup/docs.mdx
- src/molecules/cookieConsentPopup/index.jsx
- src/molecules/footer/index.jsx
- src/organisms/shell/index.jsx
- src/state/shell.js
- src/templates/aboutPage/index.jsx
- src/templates/cookiePage/cookiePage.stories.js
- src/templates/cookiePage/cookiePage.test.jsx
- src/templates/cookiePage/docs.mdx
- src/templates/cookiePage/index.jsx
- src/templates/homePage/index.jsx
> Backend maintenance, analytics, cookie policy

- .github/workflows/deploy-production.yml
Add a GitHub Action to push to the `production` branch once every 12 hours.
> [FEATURE] Add action to deploy periodically

- src/templates/aboutPage/_index.scss
- src/templates/aboutPage/index.jsx
Add new contributors, reorder and remove inactive.
> Update contributor list

- .cypress/fixtures/example.json
- .cypress/plugins/index.js
- cypress.json
- package-lock.json
- package.json
- src/templates/homePage/homePage.spec.js
- src/templates/listingPage/listingPage.spec.js
- src/templates/snippetPage/snippetPage.spec.js
> - Implement at least 2 end-to-end tests for 30-seconds-web.
In order to achieve the above OKR for Q1 (#25), we are using [Cypress](https://www.cypress.io/) to implement end-to-end testing.
> End-to-end testing

- src/functions/build/createPages/createHomePage.js
- src/functions/build/createPages/createListingPages.js
> Listing content ordering

- content/reducers/cssReducer.js
- content/reducers/es6Reducer.js
- content/reducers/jsxReducer.js
- content/reducers/stdReducer.js
- src/atoms/tag/index.jsx
- src/functions/parsers/parseSnippetContext.js
- src/functions/transformers/index.js
- src/functions/transformers/transformTags.js
- src/functions/transformers/transformTags.test.js
- src/functions/utils/array.js
- src/functions/utils/array.test.js
- src/functions/utils/index.js
- src/lang/literals_en.js
- src/molecules/previewCard/previewCard.test.jsx
- src/molecules/tagList/index.jsx
- src/shared/expertiseLevels.js
Resolves #58
Due to the nature of this change, it should be part of the blog integration (#33).
> Decouple tag formatting from React

- src/functions/build/createPages/createListingPages.js
- src/molecules/paginator/index.jsx
- src/typedefs/paginator.js
Partial implementation of #23 - only the backend work for the URLs.
> Card order options

- src/build/transformers/transformSnippets.js
- src/build/transformers/transformSnippets.test.js
- src/components/organisms/snippetCard/standardSnippetCard/_index.scss
> Enable blog body img

- src/components/atoms/pageSubtitle/index.jsx
- src/components/molecules/footer/index.jsx
- src/components/molecules/listingAnchors/index.jsx
- src/components/molecules/previewCard/index.jsx
- src/components/molecules/search/index.jsx
- src/components/molecules/search/index.test.jsx
- src/components/molecules/simpleCard/index.jsx
- src/components/molecules/sorter/index.jsx
- src/components/organisms/cta/index.jsx
- src/components/organisms/snippetCard/blogSnippetCard/index.jsx
- src/components/organisms/snippetCard/cssSnippetCard/index.jsx
- src/components/organisms/snippetCard/standardSnippetCard/index.jsx
- src/components/organisms/snippetList/index.jsx
- src/components/templates/staticPage/index.jsx
- src/utils/array.js
- src/utils/array.test.js
- src/utils/index.js
Minor across-the-board optimizations to the codebase, components and (hopefully) performance. Mainly unused props and function calls were :scissors:ed from the React code.
> React component optimizations

- src/components/molecules/search/index.jsx
- src/components/organisms/shell/index.jsx
- src/lang/en/client/common.js
> Move cookie disclaimer to end of page

- src/components/organisms/snippetCard/blogSnippetCard/index.jsx
- src/components/organisms/snippetCard/cssSnippetCard/index.jsx
- src/components/organisms/snippetCard/standardSnippetCard/index.jsx
Remove unnecessary code and minor performance hurdles.
> Optimize snippet cards

- src/build/resolvers/blogResolver.js
- src/components/atoms/card/_index.scss
- src/components/organisms/snippetCard/blogSnippetCard/_index.scss
> Fix blog list bugs

- .travis.yml
- package-lock.json
- package.json
- src/yild/extractSnippets/parseSnippets.js
Resolves #137 
Also, remove `string.prototype.matchall` import.
**Note:** Netlify needs a configuration change for this to work (via dashboard), I think.
> Bump Node version to 12.x

- src/components/molecules/footer/index.jsx
> Fix footer links

- src/components/molecules/cookieConsentPopup/_index.scss
- src/components/molecules/footer/_index.scss
- src/components/molecules/listingAnchors/_index.scss
- src/components/organisms/shell/_index.scss
- src/spec/listing.spec.js
- src/spec/search.spec.js
- Update listing anchors styles (broken in Chrome 85)
- Update layout to make it scrollable
- Resolves #170
- Resolves #149
- Resolves #111
> Make layout scrollable

- src/components/molecules/paginator/index.jsx
- src/components/molecules/paginator/index.test.jsx
> Add rel attributes to Paginator

- src/components/atoms/pageTitle/_index.scss
> Add some spacing above static page titles

- content/configs/30dart.json
- content/configs/30golang.json
- content/configs/30php.json
- content/configs/30python.json
- content/configs/30react.json
- src/build/extract/index.js
- src/build/listing/index.js
- src/build/snippet/compileSnippet.js
Related #166 
Unlisting Dart and Go and related snippets.
> Allow snippets and listings to be unlisted

- src/components/organisms/meta/index.jsx
- src/components/templates/listingPage/index.jsx
- src/components/templates/snippetPage/index.jsx
- src/fixtures/metadata.js
- src/utils/index.js
- src/utils/object.js
- src/utils/object.test.js
> Structured listing data

- src/build/transformers/transformSnippets.js
- src/build/transformers/transformSnippets.test.js
- src/build/transformers/transformTags.js
- src/components/molecules/previewCard/index.jsx
- src/components/molecules/previewCard/index.test.jsx
- src/config/tags.json
> No expertise in cards

- gatsby-browser.js
- gatsby-config.js
- package-lock.json
- package.json
- src/build/listing/index.js
- src/build/snippet/parseMarkdown.js
- src/components/atoms/codeBlock/index.jsx
- src/components/organisms/shell/_index.scss
- src/components/organisms/snippetList/index.jsx
- src/styles/_reset.scss
Minor issues cleanup and polishing.
Related #182 
Resolves #178
Resolves #179
> Post-Q3 cleanup

- src/build/snippet/parseMarkdown.js
- src/components/molecules/footer/_index.scss
- src/components/molecules/paginator/index.jsx
- src/components/organisms/shell/_index.scss
- src/components/organisms/shell/index.jsx
- src/components/organisms/snippetCard/blogSnippetCard/_index.scss
- src/styles/_global_variables.scss
Fixes #187 
Fixes #186 
Resolves #158
> UX improvements bundle

- content/configs/30csharp.json
- content/configs/30php.json
- content/configs/30python.json
- content/configs/30react.json
- src/build/snippet/compileSnippet.js
- src/engines/recommendationEngine.js
- src/spec/listing.spec.js
- static/_redirects
> Content-related updates

- src/blocks/entities/snippetCollection/index.js
- src/components/molecules/search/_index.scss
- src/components/organisms/shell/_index.scss
- src/components/organisms/shell/index.jsx
- src/config/cypress.json
- src/lang/en/listing/index.js
- src/styles/_global_variables.scss
- Resolves #242, resolves #243
- Also made some updates to the scrollbar to account for the new spacing and padding
- Made some minor changes to Cypress to allow for minimum false negatives in Travis CI
> Introduce wider navbar

- .github/workflows/tweet.yml
- src/blocks/serializers/chirp/index.js
- src/blocks/utilities/screenshot/index.js
- Clip snippets with ranking <= 0.06 from chirps
- Hide description in screenshot utility
- Reduce daily tweets to 3 (previously 4)
> Twitter bot updates

- src/blocks/utilities/screenshot/index.js
- src/settings/chirp.json
- Add description in screenshot utility
- Update hashtags
> Twitter experiment

- src/blocks/entities/collectionConfig/index.js
- src/blocks/entities/collectionConfig/index.test.js
- src/blocks/entities/snippet/index.js
- src/blocks/entities/snippet/index.test.js
- src/blocks/entities/snippetCollection/index.js
- src/blocks/entities/snippetCollection/index.test.js
- src/blocks/utilities/extractor/index.js
- src/fixtures/blocks/collectionConfigs.js
- src/utils/object.js
Related to #238 
Blocked by 30-seconds/30-seconds-content#3
> Collections stage 3

- src/blocks/adapters/snippetCollectionListing/index.js
- src/blocks/entities/snippetCollection/index.js
- src/blocks/serializers/asset/index.js
- src/components/molecules/listingAnchors/_index.scss
- src/components/organisms/snippetList/_index.scss
- src/components/organisms/snippetList/index.jsx
- src/components/templates/listingPage/index.jsx
- src/settings/paths.json
Final stage of the collections redesign.
Resolves #238 
Fixes #293 
Blocked by 30-seconds/30-seconds-content#4
> Collection images

- src/components/atoms/button/regularButton/_index.scss
- src/components/atoms/card/_index.scss
- src/components/atoms/collectionChip/_index.scss
- src/components/atoms/pageBackdrop/_index.scss
- src/components/atoms/toggle/_index.scss
- src/components/molecules/actions/_index.scss
- src/components/molecules/cookieConsentPopup/index.jsx
- src/components/molecules/listingAnchors/_index.scss
- src/components/molecules/paginator/_index.scss
- src/components/molecules/search/_index.scss
- src/components/molecules/sorter/_index.scss
- src/components/organisms/shell/_index.scss
- src/components/organisms/snippetCard/blogSnippetCard/_index.scss
- src/styles/_anchor.scss
- src/styles/_code.scss
- src/styles/_global_variables.scss
Fixes #311 
Fixes Gatsby rehydration issues
> Fix context-related bugs

- src/styles/_reset.scss
- src/styles/type/_font-styles.scss
> Customize fonts

- src/blocks/utilities/logger/index.js
- src/blocks/utilities/logger/index.test.js
- src/components/atoms/button/regularButton/_index.scss
- src/components/atoms/button/regularButton/index.jsx
- src/components/atoms/card/_index.scss
- src/components/atoms/codeBlock/index.jsx
- src/components/atoms/collectionChip/index.jsx
- src/components/atoms/pageBackdrop/index.jsx
- src/components/atoms/toggle/index.jsx
- src/components/molecules/listingAnchors/index.jsx
- src/components/molecules/paginator/_index.scss
- src/components/molecules/paginator/index.jsx
- src/components/molecules/search/_index.scss
- src/components/organisms/shell/_index.scss
- src/scripts/create.js
- src/styles/type/_anchor.scss
Resolves #332
Resolves #329
Resolves #334
> Updates and bugfixes (May 2021)

- src/components/atoms/codeBlock/_index.scss
> Fix Git snippet example title bug

- .vscode/settings.json
- src/components/atoms/breadcrumbs/_index.scss
- src/components/atoms/card/_index.scss
- src/components/atoms/codeBlock/_index.scss
- src/components/molecules/actions/_index.scss
- src/components/molecules/cookieConsentPopup/_index.scss
- src/components/molecules/paginator/_index.scss
- src/components/molecules/search/_index.scss
- src/components/organisms/recommendationList/_index.scss
- src/components/organisms/shelf/_index.scss
- src/components/organisms/shell/_index.scss
- src/components/organisms/snippetCard/blogSnippetCard/_index.scss
- src/components/organisms/snippetCard/cssSnippetCard/_index.scss
- src/components/organisms/snippetCard/standardSnippetCard/_index.scss
- src/components/organisms/snippetList/_index.scss
- src/styles/_border-radii.scss
- src/styles/_buttons.scss
- src/styles/_colors.scss
- src/styles/_fonts.scss
- src/styles/_icons.scss
- src/styles/_layout.scss
- src/styles/_reset.scss
- src/styles/_scrollbars.scss
- src/styles/_spacing.scss
- src/styles/_surfaces.scss
- src/styles/type/_anchor.scss
- src/styles/type/_code.scss
- src/styles/type/_colors.scss
- src/styles/type/_font-sizes.scss
- src/styles/type/_font-styles.scss
> Integrate Prettier for SCSS files

- src/blocks/serializers/feed/index.js
> Include React hook snippets into RSS feed

- src/components/atoms/card/index.jsx
- src/components/atoms/pageTitle/_index.scss
- src/components/molecules/cookieConsentPopup/index.jsx
- src/components/molecules/previewCard/index.jsx
- src/components/molecules/search/index.jsx
- src/scripts/develop.js
- src/styles/_expertise.scss
- src/styles/_surfaces.scss
- src/styles/type/_colors.scss
> Cosmos design system polish up

- src/components/atoms/footer/index.jsx
- src/components/molecules/search/_index.scss
- src/components/molecules/search/index.jsx
- src/components/organisms/shelf/_index.scss
- src/components/organisms/shell/_index.scss
> Mobile enhancements

- src/blocks/extractor/index.js
- src/blocks/models/language.js
- src/blocks/models/snippet.js
- src/test/fixtures/content.js
And replace with a method that uses the `Tag` model instead.
> Remove tagIcons field from Language

- package-lock.json
- package.json
- src/blocks/extractor/index.js
- src/blocks/extractor/markdownParser.js
> Snippet references

- src/blocks/application.js
- src/blocks/models/collection.js
- src/blocks/models/listing.js
- src/blocks/models/snippet.js
- src/blocks/schema.js
> Allow custom collections to belong to language collections

- .vscode/settings.json
- package-lock.json
- package.json
- src/blocks/application.js
- src/blocks/extractor/index.js
- src/blocks/utilities/ranker.js
- src/blocks/utilities/yamlHandler.js
- Related configs change: 30-seconds/30-seconds-content#24
> Convert configs to YAML

- src/blocks/utilities/content.js
- src/scripts/create.js
- Related: 30-seconds/30-seconds-of-code#1924
> Community guidelines 2023

- public/_redirects
- src/blocks/models/collection.js
- Related: 30-seconds/30-seconds-of-code#1932
> HTML collections

- public/_redirects
- Related: 30-seconds/30-seconds-of-code#1937
> Add redirects for some merged pieces

- public/_redirects
- Related: 30-seconds/30-seconds-of-code#1942
> Add redirects for some updated pieces

- src/components/Meta.astro
- src/styles/_fonts.scss
- src/styles/type/_font-styles.scss
Fonts are flashing sometimes, this is an attempt to minimize this problem.
> Attempt to minimize FOUT
